### ISSUE TITLE
flash is not defined in conditionals?

### ISSUE THREAD

**Issue by adrianrey05** [totaljs/modules#45]
hello,

i need help in this line of view

```html
@{if flash('error') == null}
	<div class="alert alert-dismissible alert-danger">
		<button type="button" class="close" data-dismiss="alert">x</button>
		<strong>@{flash('error')}</strong>
	</div>
@{fi}
```

this is the controller

```javascript
var passport = require('passport');

exports.install = function() {
  F.route('/auth', local_get, ['#session', '#flash']);
	F.route('/auth', local_login_post, ['post', '#session', '#passport.js', '#flash']);
  // or
  // F.route('/');
};

function local_get() {
	var self = this;
	self.view('index');
}

function local_login_post() {
	var self = this;
	passport.authenticate('local-login', {
		successRedirect: '/',
		failureRedirect: '/auth',
		failureFlash: true
	})(self.req, self.res);
}
```

message error: 
500: Internal Server Error :: Error: View: index - ReferenceError: flash is not defined
    at Object.Controller.view (E:\GitHub\total-faq\node_modules\total.js\index.js:12420:13)
    at Object.local_get (E:\GitHub\total-faq\controllers\auth.js:16:7)
    at Subscribe.doExecute (E:\GitHub\total-faq\node_modules\total.js\index.js:9089:23)
    at E:\GitHub\total-faq\node_modules\total.js\index.js:9022:8
    at Array._async_middleware (E:\GitHub\total-faq\node_modules\total.js\utils.js:4076:4)
    at Immediate.res.$middleware [as _onImmediate] (E:\GitHub\total-faq\node_modules\total.js\utils.js:4081:8)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by petersirka** [comment]
Hi @adrianrey05,
please try to update view like this:

```javascript
@{if helpers.flash('error') == null}
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>@{flash('error')}</strong>
    </div>
@{fi}
```
Framework doesn't support custom helpers (the module flash uses custom helper) in conditions or loops because helpers are defined in global object and the framework can reads custom helpers like this `@{flash(...)}` only. In unusual cases framework needs simple help like my code.

Give me a feedback.
Thanks.

**Comment by adrianrey05** [comment]
Hello @petersirka,
thanks for answering

update the view to 
```javascript
@{if helpers.flash('error') == null}
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <strong>@{flash('error')}</strong>
  </div>
@{fi}
```
and gives the following error
```
500: Internal Server Error :: Error: View: index - TypeError: Cannot read property 'flash' of undefined
    at Object.Controller.view (E:\GitHub\total-faq\node_modules\total.js\index.js:12420:13)
    at Object.local_get (E:\GitHub\total-faq\controllers\auth.js:17:7)
    at Subscribe.doExecute (E:\GitHub\total-faq\node_modules\total.js\index.js:9089:23)
    at E:\GitHub\total-faq\node_modules\total.js\index.js:9022:8
    at Array._async_middleware (E:\GitHub\total-faq\node_modules\total.js\utils.js:4076:4)
    at Immediate.res.$middleware [as _onImmediate] (E:\GitHub\total-faq\node_modules\total.js\utils.js:4081:8)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
this is the route in controller
```javascript
F.route('/auth', local_get, ['#session', '#flash']);
```

**Comment by petersirka** [comment]
Can you send me a small example on my email?
Thanks!

**Comment by petersirka** [comment]
Yes, you're right. My solution doesn't work :-1: ... but I found a problem in the view parser. Please download the latest beta version `npm install total.js@beta` and everthing will work.

PS: I know that you have a solution.
Thanks for the report.
